Création des Navigateurs et des écrans qui seront dedans
Xzeno15150/character-sheets-react-native pull request #4
Opened 2023-05-26 09:50 UTC by Neitah

C'est dans le titre !

2023-05-26 10:56 UTC, Xzeno15150 requested changes

2023-05-26 10:56 UTC, Xzeno15150 commented on src/screens/Character.tsx
> +export default function Character(){
Peut etre renommer les screen en CharacterScreen ou CharacterDetail peut etre

2023-05-26 10:56 UTC, Xzeno15150 commented on src/screens/Character.tsx
> +export default function Character(){
Pareil pour party d'ailleurs

2023-05-27 07:04 UTC, erpoint commented on src/screens/Character.tsx
> +export default function Character(){
:+1:

2023-05-29 12:58 UTC, Xzeno15150 approved these changes

2023-05-29 12:59 UTC, merged

2023-05-29 12:59 UTC, erpoint approved these changes