Feature/master parties
Xzeno15150/character-sheets-react-native pull request #9
Opened 2023-06-02 09:26 UTC by Xzeno15150

2023-06-02 09:36 UTC, Neitah approved these changes
ça me parait pas mal, mais c'est non contractuel

2023-06-02 09:52 UTC, erpoint requested changes

2023-06-02 09:52 UTC, erpoint commented on src/components/PartyListItemTitle.tsx
> +    party: any
Ca doit être une Party ou PartyPartial

2023-06-02 09:52 UTC, erpoint commented on src/model/enums/CharacterElement.ts
> +export enum CharacterElement {
export default ?

2023-06-02 09:52 UTC, erpoint commented on src/redux/selectors/PartySelectors.tsx
> +export const selectParties = (state : any) => state.partyReducer.parties;
any ?

2023-06-02 15:02 UTC, Xzeno15150 commented on src/model/enums/CharacterElement.ts
> +export enum CharacterElement {
oui j'arrivais pas à le faire à la base, mais du coup j'ai compris xD
parce qu'on pas mettre le default directement comme sur les functions

2023-06-02 15:02 UTC, Xzeno15150 commented on src/redux/selectors/PartySelectors.tsx
> +export const selectParties = (state : any) => state.partyReducer.parties;
faut que je remplace par un @ts-ignore

2023-06-02 15:03 UTC, Xzeno15150 commented on src/components/PartyListItemTitle.tsx
> +    party: any
ouep un oubli

2023-06-05 08:37 UTC, Neitah commented on src/components/RegisterForm.tsx
> +    const [password, setEmail] = useState("");
FIX à faire ici

2023-06-05 08:39 UTC, Neitah approved these changes

2023-06-05 09:14 UTC, erpoint approved these changes

2023-06-05 09:14 UTC, merged